#!/bin/bash

set -euo pipefail

: "${DOCKER_USER:? required}"

# build docker image
docker buildx build --no-cache --platform linux/arm64,linux/amd64 --push -t ${DOCKER_USER}/kube-sidecar-injector:v1 .
