namespace: sidecar-injector

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml
- sidecar-configmap.yaml

images:
- name: sidecar-injector
  newName: nineinchnick/kube-sidecar-injector
  newTag: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
